version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.118.129
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $$2}'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 3
    depends_on:
      - zookeeper
  kafka-manager: 
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
